package com.hastanerandevu.enums;

public enum SecretQuestionEnum {
  WHAT_IS_THE_NAME_OF_YOUR_FAVORITE_PET,
  IN_WHAT_CITY_WERE_YOU_BORN,
  WHAT_IS_YOUR_MOTHER_MAIDEN_NAME,
  WHAT_IS_YOUR_FAVORITE_COLOR,
  WHO_IS_YOUR_FAVORITE_ACTOR_MUSICIAN_OR_ARTIST,
  WHAT_IS_THE_NAME_OF_YOUR_FIRST_SCHOOL,
  WHAT_IS_YOUR_FAVORITE_MOVIE,
  WHAT_WAS_YOUR_FAVORITE_PLACE_TO_VISIT_AS_A_CHILD
}
